### ISSUE TITLE
Issue about installation

### ISSUE THREAD

**Issue by Slian22** [Rhythmicc/DrawMtxAsThumbnail#1]
`Building wheel for MtxDrawer (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [276 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build/lib.macosx-10.13-universal2-cpython-313/MtxDrawer
      copying MtxDrawer/Drawer.py -> build/lib.macosx-10.13-universal2-cpython-313/MtxDrawer
      copying MtxDrawer/__init__.py -> build/lib.macosx-10.13-universal2-cpython-313/MtxDrawer
      copying MtxDrawer/main.py -> build/lib.macosx-10.13-universal2-cpython-313/MtxDrawer
      running egg_info
      writing MtxDrawer.egg-info/PKG-INFO
      writing dependency_links to MtxDrawer.egg-info/dependency_links.txt
      writing entry points to MtxDrawer.egg-info/entry_points.txt
      writing requirements to MtxDrawer.egg-info/requires.txt`
How to install on MacOS?

**Comment by Rhythmicc** [comment]
fixed, plz install v0.0.34

**Comment by Slian22** [comment]
Still can't install. 
`pip install MtxDrawer
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (75.8.0)
Requirement already satisfied: wheel in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (0.45.1)
Collecting MtxDrawer
  Using cached mtxdrawer-0.0.34.tar.gz (83 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
          main()
          ~~~~^^
        File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 143, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/0y/wqvrsf41449_9w1pp5j05db00000gn/T/pip-build-env-_qvrn5b1/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/0y/wqvrsf41449_9w1pp5j05db00000gn/T/pip-build-env-_qvrn5b1/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/private/var/folders/0y/wqvrsf41449_9w1pp5j05db00000gn/T/pip-build-env-_qvrn5b1/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/0y/wqvrsf41449_9w1pp5j05db00000gn/T/pip-build-env-_qvrn5b1/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 2, in <module>
      ModuleNotFoundError: No module named 'Cython'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`
Maybe it's not compatible with python 3.13?

**Comment by Slian22** [comment]
Requirement already satisfied: cython

**Comment by Rhythmicc** [comment]
Fixed, plz install v0.0.35
